import{a as P,S,i as n}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const $="49354794-8d42e5f680a360b9f1765bfda",R="https://pixabay.com/api/",f=async(o,t,s)=>{try{return(await P.get(R,{params:{key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:s,page:t}})).data}catch{iziToast.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),console.error(error)}},h=document.querySelector(".gallery"),A=new S(".gallery a"),O=()=>{h.innerHTML=""},y=o=>{const t=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:r,views:a,comments:w,downloads:q})=>`<a class="gallery-item" href="${i}">
          <div class="photo-card">
            <img src="${s}" alt="${e}" />
            <div class="info">
              <p><b>Likes:</b> ${r}</p>
              <p><b>Views:</b> ${a}</p>
              <p><b>Comments:</b> ${w}</p>
              <p><b>Downloads:</b> ${q}</p>
            </div>
          </div>
        </a>`).join("");h.insertAdjacentHTML("beforeend",t),A.refresh()},p=document.querySelector(".form"),x=document.querySelector(".form-input"),b=document.querySelector(".loader"),g=document.querySelector(".load-more");let c=1,l="",m=0;const d=15;function L(){b.classList.add("active")}function u(){b.classList.remove("active")}function B(){g.style.display="block"}function v(){g.style.display="none"}p.addEventListener("submit",async o=>{if(o.preventDefault(),l=x.value.trim(),!l){n.warning({message:"Please enter a valid search query!",position:"topRight"});return}c=1,O(),L(),v();try{const t=await f(l,c,d),s=t.hits;if(u(),s.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),p.reset();return}y(s),p.reset(),m=t.totalHits,m>d&&B()}catch(t){u(),n.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),console.error(t)}});g.addEventListener("click",async()=>{c+=1,L();try{const o=Math.ceil(m/d),t=await f(l,c,d);u();const s=t.hits;y(s);const{height:i}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"}),c>=o&&(v(),n.info({message:"We're sorry, but you've reached the end of search results",position:"topRight"}))}catch(o){u(),n.error({message:"An error occurred while loading more images.",position:"topRight"}),console.error(o)}});
//# sourceMappingURL=index.js.map
